### ISSUE TITLE
Firefox has blocked automatic video playback!

### ISSUE THREAD

**Issue by fed2186** [thor-brickman/thor-brickman.github.io#1]
Hi friend! 
II tested the code and it's great to play ar in a common web browser. The only one that until recently gave no problems was firefox but with the last update they turned off the automatic playback of multimedia content and it's not nice to go into the settings and activate it ... do you have any solution for this?

**Comment by thor-brickman** [comment]
Yep, that's a browser setting that defaults to restrictive.  You would have to change it to be more open in your settings.
